
spring:
    application:
        name: canvascoding
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/canvascoding
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
                    login-url: http://localhost:8080/realms/canvascoding/protocol/openid-connect/token

    datasource:
        password: mysecretpassword
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: validate

jwt:
    auth:
        converter:
            resource-id: canvascoding-client
            principal-attribute: preferred_username

logging:
    level:
        org.springframework.security: DEBUG

server:
    port: '8081'

keycloak:
    server-url: http://localhost:8080
    realm: canvascoding
    client-secret: bYKh0Rb8ijPOSaaVA38mNWxlb6Xg2Bb2